try:
    print(number)
    
except:
    print("an error has occured")